### ISSUE TITLE
where can i find the dependcy jar

### ISSUE THREAD

**Issue by Amos-Zhao** [meteoinfo/MeteoInfoLib#2]
where can i find the dependcy jar

**Comment by Yaqiang** [comment]
You can download MeteoInfo software from the web: http://www.meteothinker.com/, the jar files are in the folder of MeteoInfo/lib.

**Comment by Amos-Zhao** [comment]
I'm trying to draw a rain contour with the guidance of this page [](http://www.cnblogs.com/songsgroup/p/5557833.html),but i encountered a error when a try to use DrawMeteoData.createShadedLayer to draw a contour layer and throw java.lang.ArrayIndexOutOfBoundsException: 0 exception,how can i fix it?

**Comment by Amos-Zhao** [comment]
`MapView mapView=new MapView();
		mapView.setBackground(new Color(255,255,255,0));
		VectorLayer clipLayer=MapDataManage.readMapFile_ShapeFile(SavePath.SHPPATH+"LinAnBorder.shp");
		
		StationData stationData=new StationData();
		List<MapRainInfoVO> vos=new CountourDAOImpl().
				queryRainInfoForContour(DateUtil.getEvenMonth(1),DateUtil.getEvenMonth(0) );
		int i=0;
		for(MapRainInfoVO vo:vos){
			//amount:121  precipitation data--- st1   34.0000 123.000 10~120mm  
			stationData.addData("st"+(++i), vo.getLgtd(), vo.getLttd(),vo.getQuery());
		}
		
		GridDataSetting gridDataSetting=new GridDataSetting();
		gridDataSetting.dataExtent=clipLayer.getExtent();
		stationData.projInfo=clipLayer.getProjInfo();
		gridDataSetting.xNum=100;
		gridDataSetting.yNum=100;
		
		InterpolationSetting interSet=new InterpolationSetting();
		interSet.setGridDataSetting(gridDataSetting);
		interSet.setInterpolationMethod(InterpolationMethods.IDW_Radius);
		interSet.setRadius(5);
		interSet.setMinPointNum(1);
		GridData gridData=stationData.interpolateData(interSet);
		
		LegendScheme legendScheme=LegendManage.createLegendSchemeFromGridData(gridData, LegendType.UniqueValue
				, ShapeTypes.Polygon);
		
		VectorLayer contourLayer=DrawMeteoData.createShadedLayer
					(gridData, legendScheme, "ContourLayer", "Data", true);
		VectorLayer lastLayer=contourLayer.clip(clipLayer);
		mapView.addLayer(lastLayer);
		
		mapView.exportToPicture("d:/1.png");`

**Comment by Amos-Zhao** [comment]
#### here is my code 

`

```java
	MapView mapView=new MapView();
	mapView.setBackground(new Color(255,255,255,0));
	VectorLayer clipLayer=MapDataManage.readMapFile_ShapeFile(SavePath.SHPPATH+"LinAnBorder.shp");
	
	StationData stationData=new StationData();
	List<MapRainInfoVO> vos=new CountourDAOImpl().
			queryRainInfoForContour(DateUtil.getEvenMonth(1),DateUtil.getEvenMonth(0) );
	int i=0;
	for(MapRainInfoVO vo:vos){
		//amount:121  precipitation data--- st1   34.0000 123.000 10~120mm  
		stationData.addData("st"+(++i), vo.getLgtd(), vo.getLttd(),vo.getQuery());
	}
	
	GridDataSetting gridDataSetting=new GridDataSetting();
	gridDataSetting.dataExtent=clipLayer.getExtent();
	stationData.projInfo=clipLayer.getProjInfo();
	gridDataSetting.xNum=100;
	gridDataSetting.yNum=100;
	
	InterpolationSetting interSet=new InterpolationSetting();
	interSet.setGridDataSetting(gridDataSetting);
	interSet.setInterpolationMethod(InterpolationMethods.IDW_Radius);
	interSet.setRadius(5);
	interSet.setMinPointNum(1);
	GridData gridData=stationData.interpolateData(interSet);
	
	LegendScheme legendScheme=LegendManage.createLegendSchemeFromGridData(gridData, LegendType.UniqueValue
			, ShapeTypes.Polygon);
	
	VectorLayer contourLayer=DrawMeteoData.createShadedLayer
				(gridData, legendScheme, "ContourLayer", "Data", true);
	VectorLayer lastLayer=contourLayer.clip(clipLayer);
	mapView.addLayer(lastLayer);
	
	mapView.exportToPicture("d:/1.png");`
```
####  and here goes the error 

`

	Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at wContour.Contour.createContourLines_UndefData(Contour.java:449)
	at wContour.Contour.tracingContourLines(Contour.java:38)
	at org.meteoinfo.drawing.ContourDraw.tracingContourLines(ContourDraw.java:81)
	at org.meteoinfo.data.meteodata.DrawMeteoData.createShadedLayer(DrawMeteoData.java:558)
`

**Comment by Yaqiang** [comment]
Suggest you to ask such question in MeteoInfo Chinese forum: http://bbs.06climate.com/forum.php .
